# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1362, 810)
        font = QtGui.QFont()
        font.setFamily("Suruma")
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(890, 470, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.with_delay = QtWidgets.QRadioButton(self.centralwidget)
        self.with_delay.setGeometry(QtCore.QRect(810, 520, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.with_delay.setFont(font)
        self.with_delay.setStyleSheet("color: rgb(0, 0, 0);")
        self.with_delay.setObjectName("with_delay")
        self.no_delay = QtWidgets.QRadioButton(self.centralwidget)
        self.no_delay.setGeometry(QtCore.QRect(810, 560, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.no_delay.setFont(font)
        self.no_delay.setStyleSheet("color: rgb(0, 0, 0);")
        self.no_delay.setObjectName("no_delay")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(840, 10, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.x = QtWidgets.QLineEdit(self.centralwidget)
        self.x.setGeometry(QtCore.QRect(900, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.x.setFont(font)
        self.x.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.x.setObjectName("x")
        self.y = QtWidgets.QLineEdit(self.centralwidget)
        self.y.setGeometry(QtCore.QRect(900, 90, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.y.setFont(font)
        self.y.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.y.setObjectName("y")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(860, 50, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(860, 90, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(800, 250, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.add.setFont(font)
        self.add.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(114, 159, 207);")
        self.add.setObjectName("add")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(860, 290, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.fill = QtWidgets.QPushButton(self.centralwidget)
        self.fill.setGeometry(QtCore.QRect(800, 600, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.fill.setFont(font)
        self.fill.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(114, 159, 207);")
        self.fill.setObjectName("fill")
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(800, 680, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.clear.setFont(font)
        self.clear.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(114, 159, 207);")
        self.clear.setObjectName("clear")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(800, 720, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exit.setFont(font)
        self.exit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(114, 159, 207);")
        self.exit.setObjectName("exit")
        self.end = QtWidgets.QPushButton(self.centralwidget)
        self.end.setGeometry(QtCore.QRect(800, 640, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.end.setFont(font)
        self.end.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(114, 159, 207);")
        self.end.setObjectName("end")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(120, 730, 661, 22))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(120, 680, 661, 22))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(1103, 10, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(1153, 40, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_9.setObjectName("label_9")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(1100, 90, 241, 551))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.table.setFont(font)
        self.table.setStyleSheet("color: rgb(0, 0, 0);")
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(860, 380, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_10.setObjectName("label_10")
        self.pixel = QtWidgets.QRadioButton(self.centralwidget)
        self.pixel.setGeometry(QtCore.QRect(800, 170, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.pixel.setFont(font)
        self.pixel.setStyleSheet("color: rgb(0, 0, 0);")
        self.pixel.setObjectName("pixel")
        self.dot = QtWidgets.QRadioButton(self.centralwidget)
        self.dot.setGeometry(QtCore.QRect(800, 130, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.dot.setFont(font)
        self.dot.setStyleSheet("color: rgb(0, 0, 0);")
        self.dot.setObjectName("dot")
        self.ellipse = QtWidgets.QRadioButton(self.centralwidget)
        self.ellipse.setGeometry(QtCore.QRect(800, 210, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.ellipse.setFont(font)
        self.ellipse.setStyleSheet("color: rgb(0, 0, 0);")
        self.ellipse.setObjectName("ellipse")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(30, 630, 751, 22))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_11.setObjectName("label_11")
        self.table_pixel = QtWidgets.QTableWidget(self.centralwidget)
        self.table_pixel.setGeometry(QtCore.QRect(1100, 720, 241, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.table_pixel.setFont(font)
        self.table_pixel.setStyleSheet("color: rgb(0, 0, 0);")
        self.table_pixel.setObjectName("table_pixel")
        self.table_pixel.setColumnCount(0)
        self.table_pixel.setRowCount(0)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(1100, 650, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(1190, 680, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_13.setObjectName("label_13")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1362, 32))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Режим"))
        self.with_delay.setText(_translate("MainWindow", "С задержкой"))
        self.no_delay.setText(_translate("MainWindow", "Без задержки"))
        self.label_2.setText(_translate("MainWindow", "Координаты точки"))
        self.label_3.setText(_translate("MainWindow", "X:"))
        self.label_4.setText(_translate("MainWindow", "Y:"))
        self.add.setText(_translate("MainWindow", "Добавить"))
        self.label_5.setText(_translate("MainWindow", "Цвет границы"))
        self.fill.setText(_translate("MainWindow", "Выполнить закраску"))
        self.clear.setText(_translate("MainWindow", "Очистить поле"))
        self.exit.setText(_translate("MainWindow", "Выход"))
        self.end.setText(_translate("MainWindow", "Замкнуть фигуру"))
        self.label_6.setText(_translate("MainWindow", "Ctrl + V - для добавления вертикального ребра"))
        self.label_7.setText(_translate("MainWindow", "Ctrl + H - для добавления горизонтального ребра"))
        self.label_8.setText(_translate("MainWindow", "Координаты введенных"))
        self.label_9.setText(_translate("MainWindow", "точек контура"))
        self.label_10.setText(_translate("MainWindow", "Цвет закраски"))
        self.pixel.setText(_translate("MainWindow", "Ввод затравочного пикселя"))
        self.dot.setText(_translate("MainWindow", "Ввод точки фигуры"))
        self.ellipse.setText(_translate("MainWindow", "Ввод кривой (эллипса)"))
        self.label_11.setText(_translate("MainWindow", "Эллипс задается двумя точками: левым верхним и нижним правым краем"))
        self.label_12.setText(_translate("MainWindow", "Координаты затравочного"))
        self.label_13.setText(_translate("MainWindow", "пикселя"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
