# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 920)
        MainWindow.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"background-color: rgb(52, 101, 164);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 20, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.label.setObjectName("label")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(40, 160, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(40, 130, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(40, 90, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(40, 60, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_5.setGeometry(QtCore.QRect(40, 190, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_6.setGeometry(QtCore.QRect(40, 220, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_7.setGeometry(QtCore.QRect(40, 420, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_7.setFont(font)
        self.radioButton_7.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_8.setGeometry(QtCore.QRect(40, 360, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_8.setFont(font)
        self.radioButton_8.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_9.setGeometry(QtCore.QRect(40, 450, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_9.setFont(font)
        self.radioButton_9.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_10 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_10.setGeometry(QtCore.QRect(40, 300, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_10.setFont(font)
        self.radioButton_10.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.radioButton_10.setObjectName("radioButton_10")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 260, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.label_2.setObjectName("label_2")
        self.radioButton_12 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_12.setGeometry(QtCore.QRect(40, 330, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_12.setFont(font)
        self.radioButton_12.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.radioButton_12.setObjectName("radioButton_12")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 570, 321, 30))
        self.pushButton.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 490, 61, 22))
        self.label_3.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 530, 61, 22))
        self.label_4.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(210, 530, 61, 22))
        self.label_5.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(210, 490, 61, 22))
        self.label_6.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(110, 490, 81, 30))
        self.lineEdit.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 530, 81, 30))
        self.lineEdit_2.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(280, 490, 81, 30))
        self.lineEdit_3.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(280, 530, 81, 30))
        self.lineEdit_4.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 650, 321, 30))
        self.pushButton_2.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 610, 85, 31))
        self.label_7.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(220, 610, 51, 31))
        self.label_8.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_8.setObjectName("label_8")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(110, 610, 81, 30))
        self.lineEdit_5.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(280, 610, 81, 30))
        self.lineEdit_6.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 700, 321, 30))
        self.pushButton_3.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 800, 321, 30))
        self.pushButton_4.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(40, 850, 321, 30))
        self.pushButton_5.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(40, 750, 321, 30))
        self.pushButton_6.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.radioButton_11 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_11.setGeometry(QtCore.QRect(40, 390, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_11.setFont(font)
        self.radioButton_11.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.radioButton_11.setObjectName("radioButton_11")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1400, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Метод"))
        self.radioButton.setText(_translate("MainWindow", "Брезенхем со сглаживанием"))
        self.radioButton_2.setText(_translate("MainWindow", "Брезенхем(float)"))
        self.radioButton_3.setText(_translate("MainWindow", "Брезенхем(int)"))
        self.radioButton_4.setText(_translate("MainWindow", "ЦДА"))
        self.radioButton_5.setText(_translate("MainWindow", "Ву"))
        self.radioButton_6.setText(_translate("MainWindow", "Библиотечный"))
        self.radioButton_7.setText(_translate("MainWindow", "Белый"))
        self.radioButton_8.setText(_translate("MainWindow", "Синий"))
        self.radioButton_9.setText(_translate("MainWindow", "Черный"))
        self.radioButton_10.setText(_translate("MainWindow", "Зеленый"))
        self.label_2.setText(_translate("MainWindow", "Цвет"))
        self.radioButton_12.setText(_translate("MainWindow", "Красный"))
        self.pushButton.setText(_translate("MainWindow", "Построить отрезок"))
        self.label_3.setText(_translate("MainWindow", "Х нач.:"))
        self.label_4.setText(_translate("MainWindow", "У нач.:"))
        self.label_5.setText(_translate("MainWindow", "У кон.:"))
        self.label_6.setText(_translate("MainWindow", "Х кон.:"))
        self.pushButton_2.setText(_translate("MainWindow", "Построить спектр"))
        self.label_7.setText(_translate("MainWindow", "Радиус:"))
        self.label_8.setText(_translate("MainWindow", "Угол:"))
        self.pushButton_3.setText(_translate("MainWindow", "Сравнить эффективность"))
        self.pushButton_4.setText(_translate("MainWindow", "Очистить поле"))
        self.pushButton_5.setText(_translate("MainWindow", "Выход"))
        self.pushButton_6.setText(_translate("MainWindow", "Сравнить ступенчатость"))
        self.radioButton_11.setText(_translate("MainWindow", "Желтый"))
