# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        font = QtGui.QFont()
        font.setFamily("Suruma")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1010, 340, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.with_delay = QtWidgets.QRadioButton(self.centralwidget)
        self.with_delay.setGeometry(QtCore.QRect(960, 390, 181, 40))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(17)
        self.with_delay.setFont(font)
        self.with_delay.setObjectName("with_delay")
        self.no_delay = QtWidgets.QRadioButton(self.centralwidget)
        self.no_delay.setGeometry(QtCore.QRect(960, 440, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(17)
        self.no_delay.setFont(font)
        self.no_delay.setObjectName("no_delay")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(950, 10, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.x = QtWidgets.QLineEdit(self.centralwidget)
        self.x.setGeometry(QtCore.QRect(1010, 60, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.x.setFont(font)
        self.x.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.x.setObjectName("x")
        self.y = QtWidgets.QLineEdit(self.centralwidget)
        self.y.setGeometry(QtCore.QRect(1010, 110, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.y.setFont(font)
        self.y.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.y.setObjectName("y")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(970, 60, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(970, 110, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(940, 170, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.add.setFont(font)
        self.add.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.add.setObjectName("add")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1010, 240, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.fill = QtWidgets.QPushButton(self.centralwidget)
        self.fill.setGeometry(QtCore.QRect(940, 500, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.fill.setFont(font)
        self.fill.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.fill.setObjectName("fill")
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(940, 640, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.clear.setFont(font)
        self.clear.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.clear.setObjectName("clear")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(940, 710, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.exit.setFont(font)
        self.exit.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.exit.setObjectName("exit")
        self.end = QtWidgets.QPushButton(self.centralwidget)
        self.end.setGeometry(QtCore.QRect(940, 570, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.end.setFont(font)
        self.end.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.end.setObjectName("end")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(260, 730, 661, 22))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(260, 680, 661, 22))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Режим"))
        self.with_delay.setText(_translate("MainWindow", "С задержкой"))
        self.no_delay.setText(_translate("MainWindow", "Без задержки"))
        self.label_2.setText(_translate("MainWindow", "Координаты точки"))
        self.label_3.setText(_translate("MainWindow", "X:"))
        self.label_4.setText(_translate("MainWindow", "Y:"))
        self.add.setText(_translate("MainWindow", "Добавить точку"))
        self.label_5.setText(_translate("MainWindow", "Цвет"))
        self.fill.setText(_translate("MainWindow", "Выполнить закраску"))
        self.clear.setText(_translate("MainWindow", "Очистить поле"))
        self.exit.setText(_translate("MainWindow", "Выход"))
        self.end.setText(_translate("MainWindow", "Замкнуть фигуру"))
        self.label_6.setText(_translate("MainWindow", "Ctrl + V - для добавления вертикального ребра"))
        self.label_7.setText(_translate("MainWindow", "Ctrl + H - для добавления горизонтального ребра"))
